"""Initial schema: all v1 tables.

Hand-written rather than autogenerated: autogenerate cannot be trusted with
the partial unique index on job.source_ref, so the whole revision is explicit
and reviewable. Keep it in sync with app/models.py.

Note on enums: ``sa.Enum(...)`` renders as plain VARCHAR on SQLite — the DB
does not enforce enum validity (no CHECK constraint). That is a deliberate
v1 choice: valid values are enforced at the ORM/API layer only (see the
enums section in app/models.py).

Revision ID: 0001
Revises:
Create Date: 2026-07-25

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("position", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("not_started", "applied", "denied", "accepted", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column("denied_at", sa.DateTime(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("manual", "recommended", name="jobsource"),
            nullable=False,
        ),
        sa.Column("source_ref", sa.String(), nullable=True),
        sa.Column("dedup_hash", sa.String(), nullable=False),
        sa.Column("dismissed_at", sa.DateTime(), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("match_rationale", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )
    # Partial unique index: dedup backstop for provider postings only —
    # manual jobs have source_ref NULL and must coexist freely. Written by
    # hand because autogenerate does not handle sqlite_where.
    op.create_index(
        "uq_job_source_ref",
        "job",
        ["source_ref"],
        unique=True,
        sqlite_where=sa.text("source_ref IS NOT NULL"),
    )
    op.create_index("ix_job_dedup_hash", "job", ["dedup_hash"], unique=False)

    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
    )

    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
    )

    op.create_table(
        "joblink",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
    )

    op.create_table(
        "resumesection",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
    )

    op.create_table(
        "mastersnapshot",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )

    op.create_table(
        "mastersnapshotsection",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["mastersnapshot.id"], ondelete="CASCADE"
        ),
    )

    op.create_table(
        "tailoredresume",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("is_submitted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
    )

    op.create_table(
        "tailoredsection",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("tailored_resume_id", sa.Integer(), nullable=False),
        sa.Column("base_section_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("changed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tailored_resume_id"], ["tailoredresume.id"], ondelete="CASCADE"
        ),
        # Provenance link only — a deleted master section must not take the
        # tailored copy's content with it.
        sa.ForeignKeyConstraint(
            ["base_section_id"], ["resumesection.id"], ondelete="SET NULL"
        ),
    )

    op.create_table(
        "configprofile",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("experience", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("pay_min", sa.Integer(), nullable=True),
    )

    op.create_table(
        "experiencesource",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "type",
            sa.Enum(
                "resume", "case_study", "webpage", "manual",
                name="experiencesourcetype",
            ),
            nullable=False,
        ),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
    )


def downgrade() -> None:
    # Children before parents (FK order).
    op.drop_table("experiencesource")
    op.drop_table("configprofile")
    op.drop_table("tailoredsection")
    op.drop_table("tailoredresume")
    op.drop_table("mastersnapshotsection")
    op.drop_table("mastersnapshot")
    op.drop_table("resumesection")
    op.drop_table("joblink")
    op.drop_table("contact")
    op.drop_table("comment")
    op.drop_index("ix_job_dedup_hash", table_name="job")
    op.drop_index("uq_job_source_ref", table_name="job")
    op.drop_table("job")
